# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: nf-core-bamtofastq-1.0dev
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bioconda::multiqc=1.9
  - bioconda::samtools=1.10
  - bioconda::fastqc=0.11.9
  - conda-forge::r-markdown=1.1
  - conda-forge::r-base=3.6.1
  - conda-forge::pigz=2.3.4
